SELECT CONCAT(CONCAT(INITCAP(M.NUME), ' '), INITCAP(M.PRENUME)) AS MEMBRU, M.ID_DEPARTAMENT, D.ID_CLUB, C.ID_FILIALA, M.DATA_ADERARE, 
ROUND(MONTHS_BETWEEN(SYSDATE, M.DATA_ADERARE), 0) AS LUNI
FROM MEMBRI_ACTIVI M
JOIN DEPARTAMENTE D
ON(M.ID_DEPARTAMENT = D.ID_DEPARTAMENT)
JOIN CLUBURI C
ON(C.ID_CLUB = D.ID_CLUB)
WHERE M.DATA_ADERARE <= ALL(SELECT M1.DATA_ADERARE
                        			FROM MEMBRI_ACTIVI M1
                        WHERE M1.ID_DEPARTAMENT = M.ID_DEPARTAMENT)
ORDER BY M.ID_DEPARTAMENT;
