WITH SUME AS (SELECT NVL(SUM(S1.SUMA), 0) AS TOTAL
                	FROM SPONSORI S1
                	RIGHT JOIN PROIECT P1 
                	ON (S1.ID_PROIECT = P1.ID_PROIECT)
                	GROUP BY P1.ID_PROIECT)
                
SELECT P.TITLU_PROIECT, NVL(SUM(S.SUMA), 0) AS SUMA
FROM PROIECT P
LEFT JOIN SPONSORI S 
ON (P.ID_PROIECT = S.ID_PROIECT)
GROUP BY P.ID_PROIECT, P.TITLU_PROIECT
HAVING NVL(SUM(S.SUMA), 0) = (SELECT MAX(TOTAL) FROM SUME);
